CREATE TABLE IF NOT EXISTS players (
  id INT PRIMARY KEY,
  nation_name VARCHAR(120) NOT NULL,
  treasury BIGINT NOT NULL DEFAULT 0,
  population BIGINT NOT NULL DEFAULT 0,
  soldiers INT NOT NULL DEFAULT 0,
  influence INT NOT NULL DEFAULT 0,
  updated_at DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS settings (
  `key` VARCHAR(80) PRIMARY KEY,
  `value` TEXT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
