<!doctype html><html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><title>Map</title><link rel='stylesheet' href='/assets/css/ui.css'><link rel='stylesheet' href='/assets/css/components.css'><link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css'><link rel='stylesheet' href='https://unpkg.com/leaflet@1.9.4/dist/leaflet.css'><style>#map{height:72vh;border-radius:16px;border:1px solid #2c3c5e}.float{position:absolute;right:20px;top:96px;max-width:360px;z-index:500}.hud{position:absolute;left:16px;top:96px;max-width:320px;z-index:500}</style></head><body><script src='/assets/js/ui.js'></script><script src='https://unpkg.com/leaflet@1.9.4/dist/leaflet.js'></script><script>
UX.shell('/map',`<div style='position:relative'><div id='map'></div><div class='glass-card hud' id='travelHud' style='display:none'></div><div class='glass-card float' id='panel'><h3>Region Intel</h3><div class='sub'>Select a region</div></div></div>`);
const map=L.map('map').setView([41,29],5);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:13}).addTo(map);
let regions=[],me=null,tstate=null;
const fmt=s=>{s=Math.max(0,Number(s||0));return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;};
(async()=>{try{regions=await UX.api('/api/map/regions');try{me=await UX.api('/api/player/me')}catch{};
if(me?.is_traveling&&me?.travel){tstate={remaining:Number(me.travel.remaining_seconds||0),pct:Number(me.travel.progress_percent||0)};travelHud.style.display='block';renderTravel();}
regions.forEach(r=>{const m=L.circleMarker([Number(r.lat),Number(r.lng)],{radius:6,color:'#89b4ff',fillColor:'#3b82f6',fillOpacity:.6}).addTo(map);m.on('mouseover',()=>m.setStyle({radius:8}));m.on('mouseout',()=>m.setStyle({radius:6}));m.on('click',()=>show(r));});}catch(e){panel.innerHTML=e.message;}})();
function dist(a,b,c,d){const R=6371,dl=(c-a)*Math.PI/180,dg=(d-b)*Math.PI/180,x=Math.sin(dl/2)**2+Math.cos(a*Math.PI/180)*Math.cos(c*Math.PI/180)*Math.sin(dg/2)**2;return R*(2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x)));}
function show(r){let d='-';if(me){const cur=regions.find(x=>Number(x.id)===Number(me.current_region_id));if(cur)d=Math.round(dist(Number(cur.lat),Number(cur.lng),Number(r.lat),Number(r.lng)))+' km';}
panel.innerHTML=`<h3>${r.name}</h3><div class='sub'>${r.country_name}</div><p>Population: ${UX.fmt(r.population)}</p><p class='resource'>🧪 ${r.resource_type||'-'}</p><p>Distance: ${d}</p><div style='display:flex;gap:8px'><a class='btn alt' href='/region/${r.id}'>Open Detail</a><button class='btn ${tstate?'pulse':''}' id='tv' ${tstate?'disabled':''}>${tstate?'Traveling...':'Travel'}</button></div><small id='hint' class='sub'></small>`;
const b=document.getElementById('tv'); if(b) b.onclick=async()=>{try{await UX.api('/api/region/action',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({region_id:r.id,action:'travel'})});hint.textContent='Travel started';}catch(e){hint.textContent=e.message}};}
function renderTravel(){if(!tstate)return;travelHud.innerHTML=`<h4 class='pulse'>✈ Traveling...</h4><div class='sub'>Countdown: ${fmt(tstate.remaining)}</div><div class='progress'><i style='width:${tstate.pct}%'></i></div>`;}
setInterval(()=>{if(tstate&&tstate.remaining>0){tstate.remaining--;renderTravel();}},1000);
</script></body></html>
