<!doctype html><html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><title>Profile</title><link rel='stylesheet' href='/assets/css/ui.css'><link rel='stylesheet' href='/assets/css/components.css'><link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css'></head><body><script src='https://cdn.socket.io/4.7.5/socket.io.min.js'></script><script src='/assets/js/ui.js'></script><script>
UX.shell('/profile',`<div class='grid cols-3'><div class='glass-card' id='base'></div><div class='glass-card' id='economy'></div><div class='glass-card' id='nation'></div></div><div class='glass-card' style='margin-top:12px'><h3>Stat Lab</h3><div id='gstats' class='sub'></div><div class='tabs' id='tabs'><button class='tab active' data-s='strength'>💪 Strength</button><button class='tab' data-s='education'>📘 Education</button><button class='tab' data-s='endurance'>🛡 Endurance</button></div><div id='sinfo' class='sub'></div><div class='progress'><i id='sbar' style='width:0%'></i></div><small id='scd' class='sub'></small><div style='display:flex;gap:8px;margin-top:8px'><button id='coin' class='btn'></button><button id='gold' class='btn'></button><button id='stop' class='btn alt'>Stop</button></div></div><div class='glass-card' style='margin-top:12px'><h3>Travel</h3><div id='travel' class='sub'></div><button id='cancel' class='btn alt'>Cancel Travel</button></div>`);
let me=null, sel='strength', st=null;
const fmt=s=>{s=Math.max(0,Number(s||0));return `${String(Math.floor(s/3600)).padStart(2,'0')}:${String(Math.floor((s%3600)/60)).padStart(2,'0')}:${String(Math.floor(s%60)).padStart(2,'0')}`;};
async function preview(){try{return await UX.api('/api/player/stat-preview?stat='+sel);}catch{return null;}}
async function load(){me=(await UX.api('/api/player/me'));base.innerHTML=`<h3>${me.username}</h3><div class='sub'>Level ${me.level} • ${me.current_region_name}</div><div class='progress'><i style='width:${Math.round((me.xp/me.xp_to_next)*100)}%'></i></div><small class='sub'>XP ${me.xp}/${me.xp_to_next}</small>`;economy.innerHTML=`<h3>Economy</h3><div class='kpi'>🪙 ${UX.fmt(me.coins)}</div><div class='kpi'>💎 ${UX.fmt(me.gold)}</div><div class='sub'>Energy ${me.instant_energy}/${me.max_instant_energy}</div>`;nation.innerHTML=`<h3>Nation</h3><div class='sub'>${me.nation_name||'-'}</div>`;gstats.textContent=`STR ${me.strength} • EDU ${me.education} • END ${me.endurance}`;const p=await preview();if(p){sinfo.textContent=`${sel.toUpperCase()} Lv ${p.level} • 🪙 ${UX.fmt(p.coins_cost)} / ${Math.ceil(p.coins_duration_seconds/60)} dk • 💎 ${UX.fmt(p.gold_cost)} / ${Math.ceil(p.gold_duration_seconds/60)} dk`;coin.textContent=`Start Coin (${UX.fmt(p.coins_cost)})`;gold.textContent=`Start Gold (${UX.fmt(p.gold_cost)})`;}
const active=!!me.active_stat;coin.disabled=active;gold.disabled=active;tabs.querySelectorAll('.tab').forEach(x=>x.disabled=active);stop.disabled=!active;
if(active){const end=new Date(String(me.stat_finish_time).replace(' ','T')).getTime()/1000;const start=new Date(String(me.stat_started_at).replace(' ','T')).getTime()/1000;const rem=Math.max(0,Math.floor(end-Date.now()/1000));const tot=Math.max(1,end-start);st={rem,tot,name:me.active_stat};sbar.style.width=`${Math.round(((tot-rem)/tot)*100)}%`;scd.textContent=`${me.active_stat} ${fmt(rem)}`;}else{st=null;sbar.style.width='0%';scd.textContent='No active stat';}
if(me.is_traveling&&me.travel){travel.textContent=`${me.travel.from_region_name||me.travel.from_region_id} → ${me.travel.to_region_name||me.travel.to_region_id} | ${fmt(me.travel.remaining_seconds)}`;cancel.style.display='inline-block';}else{travel.textContent='No active travel';cancel.style.display='none';}
}
setInterval(()=>{if(st&&st.rem>0){st.rem--;sbar.style.width=`${Math.round(((st.tot-st.rem)/st.tot)*100)}%`;scd.textContent=`${st.name} ${fmt(st.rem)}`;}},1000);setInterval(load,5000);
coin.onclick=async()=>{await UX.api('/api/player/start-stat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({stat:sel,mode:'coins'})});load();};
gold.onclick=async()=>{await UX.api('/api/player/start-stat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({stat:sel,mode:'gold'})});load();};
stop.onclick=async()=>{await UX.api('/api/player/stop-stat',{method:'POST'});load();};
cancel.onclick=async()=>{await UX.api('/api/player/cancel-travel',{method:'POST'});load();};
document.querySelectorAll('[data-s]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-s]').forEach(x=>x.classList.remove('active'));b.classList.add('active');sel=b.dataset.s;load();});
load();
</script></body></html>
