<!doctype html><html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><title>Rankings</title><link rel='stylesheet' href='/styles.css'><link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css'></head><body><div class='page'><div class='hero'><h2>Rankings</h2><div class='search-row'><input id='q' placeholder='Search'><select id='sort'><option value='desc'>Desc</option><option value='asc'>Asc</option></select></div></div><div class='card'><div style='display:flex;gap:8px;margin-bottom:8px'><button class='stat-tab active' data-tab='regions'>Regions</button><button class='stat-tab' data-tab='countries'>Countries</button><button class='stat-tab' data-tab='players'>Players</button></div><div id='rows' class='list'></div></div></div><script src='/ui.js'></script><script>
GameUI.mountShell('/rankings');
let tab='regions', data={regions:[],countries:[],players:[]};
(async()=>{const d=await GameUI.api('/api/stats/dashboard'); data.regions=d.top_regions||[]; data.countries=d.top_countries||[]; data.players=(d.top_region_population||[]).map(x=>({id:x.id,name:`Leader ${x.name}`,score:Number(x.total_population||0)})); render();})();
function color(v){v=Number(v||0); return v<=2?'stat-red':v<=5?'stat-yellow':'stat-green';}
function render(){const s=(q.value||'').toLowerCase(); const asc=sort.value==='asc'; let arr=(data[tab]||[]).filter(x=>JSON.stringify(x).toLowerCase().includes(s)); arr.sort((a,b)=>asc?(Number(a.score||a.total_score||0)-Number(b.score||b.total_score||0)):(Number(b.score||b.total_score||0)-Number(a.score||a.total_score||0))); rows.innerHTML=arr.slice(0,50).map((r,i)=>{const val=Number(r.score||r.total_score||0); const name=r.name||r.country_name||('Player '+(r.id||'')); const href=tab==='regions'?`/region/${r.id}`:tab==='countries'?`/country/${r.id}`:`/player/${r.id}`; return `<a class='list-row' href='${href}'><span>${GameUI.rankBadge(i)} ${name}</span><span><i class='stat-dot ${color(val)}'></i>${GameUI.fmt(val)}</span></a>`;}).join('');}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;document.querySelectorAll('[data-tab]').forEach(x=>x.classList.remove('active'));b.classList.add('active');render();});
q.oninput=render; sort.onchange=render;
</script></body></html>
