ALTER TABLE player_profiles
    ADD COLUMN IF NOT EXISTS level INT NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS xp INT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS xp_to_next INT NOT NULL DEFAULT 100,
    ADD COLUMN IF NOT EXISTS gold DECIMAL(15,2) NOT NULL DEFAULT 1000,
    ADD COLUMN IF NOT EXISTS coins DECIMAL(15,2) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS max_energy INT NOT NULL DEFAULT 100,
    ADD COLUMN IF NOT EXISTS last_energy_update DATETIME NULL;

UPDATE player_profiles
SET last_energy_update = COALESCE(last_energy_update, NOW());
