ALTER TABLE regions
    ADD COLUMN IF NOT EXISTS army_level INT NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS education_level INT NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS hospital_level INT NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS airport_level INT NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS port_level INT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS is_coastal TINYINT(1) NOT NULL DEFAULT 0;
